### PR TITLE
adding notification in contact list

### PR DESCRIPTION
**Pull request by Miminiverse**

### CODE REVIEW

**Comment by secch97** [comment]
Hi @Miminiverse I did some changes:

- Now Talckatoo renders a **bird icon** when a new message is received and unread (:.
  - This bird icon will be rendered with an animation.
  - This icon will only render when the conversation **is not** selected. If the conversation is selected and a new message is received, the conversation will be updated to avoid having unread messages.

Please see demo:
ezgif com-video-to-gif

**Review by Miminiverse — COMMENTED** [review]
This is great working awesome! I like the tiny birds!

**Review by Said-laasri — APPROVED** [review]
Great Job !! @Miminiverse 

When both users are online the notification works amazing ! :+1: 

`I would suggest that when one user is offline and receives a new message he should see when he joins again the notification from the person who sent him `



Great Job on this feature again :1st_place_medal:

**Review by Said-laasri — APPROVED** [review]
Great Job !! @Miminiverse 

When both users are online the notification works amazing ! :+1: 

`I would suggest that when one user is offline and receives a new message he should see when he joins again the notification from the person who sent him `



Great Job on this feature again :1st_place_medal:

**Pull request merged**
