### PR TITLE
Latest message: Alignment: Fix

### PR DESCRIPTION
**Pull request by secch97**
This PR solves #15.

- Friends Tab:
  - Latest message & username alignment is now fixed: Now every chat has the same dimensions no matter the message length.
  - image

- People Tab:
  - Usernames alignment is now fixed: now every chat has the same dimensions no matter the username length.
  - image

- Corrected UserList types on Chat.tsx.
- Corrected type of React.FC<{}> on FetchLatestMessages.tsx

### CODE REVIEW

**Review by Said-laasri — APPROVED** [review]
Great Job :100:  @secch97 

Please remove the console.log in the chat.TSX

all is looking good

**Review by Said-laasri — APPROVED** [review]
Great Job :100:  @secch97 

Please remove the console.log in the chat.TSX =========>>>
Screenshot from 2023-10-03 16-10-43



all is looking good

**Comment by secch97** [comment]
- @Said-laasri Done ✅
- @Miminiverse  Done ✅
  - image

Let me know your thoughts ☺

**Comment by Miminiverse** [comment]
Ty! perfect!

**Pull request merged**
