### PR TITLE
Translation bar - Fix

### PR DESCRIPTION
**Pull request by secch97**
This PR solves #27.

- Translation bar now remains hidden if no chat is selected.
  image
- Translation bar hides when user changes chat views (e.g: from friends to people):
- Translation bar renders when a chat is selected:
  - Modified translation bar design to easily understand user's preferred language on both ends.
  image
  image

### CODE REVIEW

**Review by Said-laasri — APPROVED** [review]
@secch97  Great job on that bar looks really nice 



`just make sure you don't have any conflict with the dev branch as I can see your branch still has old sign-in design `

**Comment by Said-laasri** [comment]
@secch97  you don't have the latest update from the dev 
Screenshot from 2023-10-24 00-02-21
Screenshot from 2023-10-24 00-02-26

and on the dev branch
Screenshot from 2023-10-24 00-03-39

**Comment by secch97** [comment]
Nice catch Said, I thought I had the latest dev branch. I already merged dev into this branch, can you check again please?

**Comment by secch97** [comment]
> @secch97 Great job on that bar looks really nice
> 
>  [ 68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966 ](https://camo.githubusercontent.com/0bb7cfb48cd64bbc43d1cca144a5f8030285aaf94a6f7096c0d97d861f10e10c/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966) [ ](https://camo.githubusercontent.com/0bb7cfb48cd64bbc43d1cca144a5f8030285aaf94a6f7096c0d97d861f10e10c/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966)
> 
> `just make sure you don't have any conflict with the dev branch as I can see your branch still has old sign-in design `

Thank you!

**Comment by Miminiverse** [comment]
This is very nice the new language indicator bar!  Yep you got everything from the dev I think we are good to go!!! Please merge @secch97

**Review by Miminiverse — APPROVED** [review]

**Review by Said-laasri — APPROVED** [review]
@secch97 Great Job everything is good to go :+1: 



Great Job

**Pull request merged**
