### PR TITLE
Login page - Logic, CSS & Layout updates

### PR DESCRIPTION
**Pull request by secch97**
The present PR adds:

- Responsiveness to the Login and Register pages. The website is now able to be seen on any device without breaking the layout.
  - **Desktop:**
    image
   
   image

  - **Mobile:**
  
    image

    image
 
    image

- Modified validation logic for login page: now if any entry is invalid, request won't be sent and user will be shown a toast notification:
 
image

- Modified "show password" icon to white when dark mode is activated for login and register page:
image

image

### CODE REVIEW

**Comment by Miminiverse** [comment]
Thanks Saul for this. I'd also wait for Said to see how the view looks like on his end. He was mostly in charge of the login,  register and main page, and somehow it always rendered differently on my computer and his computer 
I just have a small add in:
1/ Can we bring * all fields are required to the bottom below the selectLanguage? Because it's also a required field
2/ IN the register page, do you have a rolling or no? On my screen I have the rolling bar on the right side

**Comment by secch97** [comment]
> Thanks Saul for this. I'd also wait for Said to see how the view looks like on his end. He was mostly in charge of the login, register and main page, and somehow it always rendered differently on my computer and his computer I just have a small add in: 1/ Can we bring * all fields are required to the bottom below the selectLanguage? Because it's also a required field 2/ IN the register page, do you have a rolling or no? On my screen I have the rolling bar on the right side

Hi Tam, thanks for your valuable feedback. I can sure bring the required message to the bottom.

Also, would you like to explain to me what do you mean by a rolling bar? Do you mean a scrolling bar? Can you show me that bar on your screen?

**Comment by Miminiverse** [comment]
> > Thanks Saul for this. I'd also wait for Said to see how the view looks like on his end. He was mostly in charge of the login, register and main page, and somehow it always rendered differently on my computer and his computer I just have a small add in: 1/ Can we bring * all fields are required to the bottom below the selectLanguage? Because it's also a required field 2/ IN the register page, do you have a rolling or no? On my screen I have the rolling bar on the right side
> 
> Hi Tam, thanks for your valuable feedback. I can sure bring the required message to the bottom.
> 
> Also, would you like to explain to me what do you mean by a rolling bar? Do you mean a scrolling bar? Can you show me that bar on your screen?

Can we not have the scrolling bar? Like user will just see a static page and the screen fits  entirely without the scrolling bar

**Comment by Said-laasri** [comment]
@secch97 looks good it responsive now and maybe some small design changes later will come 

:100: Great job :1st_place_medal:

**Review by Said-laasri — APPROVED** [review]
@secch97 Great job on the changes you made 
@Miminiverse  i think you should approve it after you review it

**Comment by secch97** [comment]
> > > Thanks Saul for this. I'd also wait for Said to see how the view looks like on his end. He was mostly in charge of the login, register and main page, and somehow it always rendered differently on my computer and his computer I just have a small add in: 1/ Can we bring * all fields are required to the bottom below the selectLanguage? Because it's also a required field 2/ IN the register page, do you have a rolling or no? On my screen I have the rolling bar on the right side
> > 
> > 
> > Hi Tam, thanks for your valuable feedback. I can sure bring the required message to the bottom.
> > Also, would you like to explain to me what do you mean by a rolling bar? Do you mean a scrolling bar? Can you show me that bar on your screen?
> 
> Can we not have the scrolling bar? Like user will just see a static page and the screen fits entirely without the scrolling bar

Hi Tam, thanks for your feedback. I have tried my best to avoid rendering a scrollbar into the page. The thing here is that the sign up form takes too much space due to it being on a column direction with many fields to fill. That's why I modified the margin, padding based on screen size. 


I also moved the all fields required message below the language selection.

Take a look:

Desktop:
image
image

Mobile:
image

The containers have an "auto" value for their heights. If i give it a fixed value then it breaks the layout.

**Comment by secch97** [comment]
I also added animations for the error messages. Please give your feedback about this.

**Comment by secch97** [comment]
> @secch97 Great job on the changes you made @Miminiverse i think you should approve it after you review it
> 
>  [ 68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f645664497531484e78654b79717a6b6750412f67697068792e676966 ](https://camo.githubusercontent.com/ab5aa4846d8a1b3d60613db2ec3ae9de685337ef80216b46f472e111a3cd2b9d/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f645664497531484e78654b79717a6b6750412f67697068792e676966) [ ](https://camo.githubusercontent.com/ab5aa4846d8a1b3d60613db2ec3ae9de685337ef80216b46f472e111a3cd2b9d/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f645664497531484e78654b79717a6b6750412f67697068792e676966)

Thank you very much! Glad to know you like it (:

**Comment by Said-laasri** [comment]
@secch97  the last update you made is a bit small on screen too small acually

Screenshot from 2023-09-23 22-32-50

**Comment by Miminiverse** [comment]
The star is black, not red like the others, plus can we make it not all red in the beginning, like it will only be red after the user fill in the form and there's some errors? I think it make more sense when you first open a form, you won't get any errors (the red star notifications). This wasn't fixed last time so can we fix this as well? We can hop on a call if it's not clear enough.
 
image

**Comment by secch97** [comment]
Hi @Said-laasri please review again the new changes. Hope it looks better now. Also fixed some animation and hover effects that were already on the code on these pages.

**Comment by secch97** [comment]
> The star is black, not red like the others, plus can we make it not all red in the beginning, like it will only be red after the user fill in the form and there's some errors? I think it make more sense when you first open a form, you won't get any errors (the red star notifications). This wasn't fixed last time so can we fix this as well? We can hop on a call if it's not clear enough.
> 
> image

Hey Tam!, Please check again the new deployed version. Let me know your feedback.

**Review by Miminiverse — APPROVED** [review]
Super nice! All good!

**Pull request merged**
